const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

module.exports = {
	devtool: "inline-source-map",
	mode: "development",
	entry: "./src/index.js",
	devServer: {
		contentBase: "./dist",
		hot: true,
	},
	output: {
		path: `${__dirname}/__build__`,
		filename: "[name].[hash].js",
		chunkFilename: "[name].[hash].chunk.js",
		publicPath: "/",
		globalObject: "this",
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: "index.html",
			inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
		}),
		new MiniCssExtractPlugin(),
		new CleanWebpackPlugin({
			filename: "[name].[hash].css",
			chunkFilename: "[id].[hash].css",
		}),
	],
	module: {
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: /(node_modules)/,
				use: {
					loader: "babel-loader",
					options: {
						presets: ["@babel/preset-env"],
						plugins: ["@babel/plugin-proposal-object-rest-spread"],
					},
				},
			},
			{
				test: /\.(html|png|jpe?g|gif|eot|ttf|woff|woff2)$/i,
				loader: "url-loader",
				options: {
					limit: 8192,
				},
				exclude: [/index.html/],
			},
			{
				test: /\.css$/,
				use: [
					MiniCssExtractPlugin.loader,
					{
						loader: "css-loader",
						options: {
							modules: true,
						},
					},
				],

				exclude: /global.css/,
			},
			{
				test: /\.svg$/,
				use: "file-loader",
			},
			{
				test: [/global.css/],
				use: [
					"style-loader",
					{
						loader: "css-loader",
						options: {
							sourceMap: true,
						},
					},
					"postcss-loader",
				],
			},
		],
	},
	resolve: {
		extensions: [".js", ".jsx", ".css"],
	},
};
