const path = require("path");

const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

module.exports = {
	devtool: "inline-source-map",
	mode: "development",
	entry: "./src/index.js",
	devServer: {
		contentBase: "./dist",
		hot: true,
	},
	output: {
		path: `${__dirname}/__build__`,
		filename: "[name].[hash].js",
		chunkFilename: "[name].[hash].chunk.js",
		publicPath: "/",
		globalObject: "this",
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: "index.html",
			inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
		}),
		new MiniCssExtractPlugin(),
		new CleanWebpackPlugin(),
	],
	module: {
		rules: [
			{
				test: /\.html$/,
				loader: "url-loader",
				exclude: [/index.html/],
			},
			{
				test: /\.css$/,
				use: ["css-loader"],
			},
			{
				test: /\.(js|jsx)$/,
				exclude: /(node_modules)/,
				use: {
					loader: "babel-loader",
					options: {
						presets: ["@babel/preset-env"],
						plugins: ["@babel/plugin-proposal-object-rest-spread"],
					},
				},
			},
		],
	},
	resolve: {
		extensions: [".js", ".jsx"],
	},
};
